/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"fmt"
)

// SecurityMonitoringRuleType Type of the rule.
type SecurityMonitoringRuleType string

// List of SecurityMonitoringRuleType
const (
	SECURITYMONITORINGRULETYPE_LOG_DETECTION SecurityMonitoringRuleType = "log_detection"
	SECURITYMONITORINGRULETYPE_CONFIGURATION SecurityMonitoringRuleType = "configuration"
)

var allowedSecurityMonitoringRuleTypeEnumValues = []SecurityMonitoringRuleType{
	"log_detection",
	"configuration",
}

func (v *SecurityMonitoringRuleType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SecurityMonitoringRuleType(value)
	for _, existing := range allowedSecurityMonitoringRuleTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SecurityMonitoringRuleType", value)
}

// NewSecurityMonitoringRuleTypeFromValue returns a pointer to a valid SecurityMonitoringRuleType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSecurityMonitoringRuleTypeFromValue(v string) (*SecurityMonitoringRuleType, error) {
	ev := SecurityMonitoringRuleType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SecurityMonitoringRuleType: valid values are %v", v, allowedSecurityMonitoringRuleTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SecurityMonitoringRuleType) IsValid() bool {
	for _, existing := range allowedSecurityMonitoringRuleTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SecurityMonitoringRuleType value
func (v SecurityMonitoringRuleType) Ptr() *SecurityMonitoringRuleType {
	return &v
}

type NullableSecurityMonitoringRuleType struct {
	value *SecurityMonitoringRuleType
	isSet bool
}

func (v NullableSecurityMonitoringRuleType) Get() *SecurityMonitoringRuleType {
	return v.value
}

func (v *NullableSecurityMonitoringRuleType) Set(val *SecurityMonitoringRuleType) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityMonitoringRuleType) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityMonitoringRuleType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityMonitoringRuleType(val *SecurityMonitoringRuleType) *NullableSecurityMonitoringRuleType {
	return &NullableSecurityMonitoringRuleType{value: val, isSet: true}
}

func (v NullableSecurityMonitoringRuleType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityMonitoringRuleType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
